### ISSUE TITLE
handle additional types of WPS base URLs

### ISSUE THREAD

**Issue by tomkralidis** [opengeospatial/ets-wps10#10]
When testing against CITE WPS beta, entering the input URL as `http://host:8000` results in errors because the test suite is constructing URLs like `http://host:8000?service=WPS...`.

Update the request handling to bind to account additional types of URL inputs:
- `http://host:8000`
- `http://host/wps?foo=bar`
- `http://host/wps?foo=bar&`

Implementation example: https://github.com/geopython/pycsw/blob/master/pycsw/core/util.py#L367

**Comment by lgoltz** [comment]
@tomkralidis Does the problem still occurs? Can you explain the problem in more detail?

**Comment by tomkralidis** [comment]
Hi @lgoltz looks like this was somehow fixed.  Thanks.
