### ISSUE TITLE
Update CTL with better information about conformance classes

### ISSUE THREAD

**Issue by keshav-nangare** [opengeospatial/ets-wps10#12]
The test needs to be updated to better provide information about the grouping of the conformance class and determination about which ones are the basic conformance classes needed for certification.

Changes that are required are described here:

https://github.com/opengeospatial/cite/wiki/Encoding-Conformance-Classes

**Comment by lgoltz** [comment]
Test are currently not structured but there can be identified three groups of tests:
 * GetCapabilities
 * DescribeProcess
 * Execute

The specification does not specify any conformance classes but as all of the three operations are mandatory I think all of them can be configured as basic.

**Comment by lgoltz** [comment]
Test was restructured and CCs configured (PR #14). Not tested yet as no service is available.

**Comment by dstenger** [comment]
Currently, tests on third level are configured as basic conformance class and thus the HTML report is empty.

Three test groups in the bottom are configured as basic CC:

![ets-wps10](https://user-images.githubusercontent.com/2989166/42153695-3075b95e-7de4-11e8-9a17-3b9d7dcf6aab.png)

The basic CC configuration was moved to wps:ows-main, wps:general-main and wps:core-main and is on second level now

Commit: https://github.com/opengeospatial/ets-wps10/commit/884f69b9bef900f832bd3ffaead5e99aab972032

Now, the HTML report is displayed correctly.

![ets-wps10-new-html-report](https://user-images.githubusercontent.com/2989166/42154618-8bb7e128-7de6-11e8-8cbe-cebf1cf4d8d9.png)
