### ISSUE TITLE
Test didn't run completely on docker teamengine

### ISSUE THREAD

**Issue by arieslai** [opengeospatial/ets-wps10#16]
I am trying to add a new upload control inside the wps10-suite.ctl file, which id is "fileExecuteRequestFileRawDataOutput", and the corresponding entry key in the test suite is "execute_request_file_raw_data_output". 
(https://github.com/opengeospatial/ets-wps10/blob/testng-develop/src/main/scripts/ctl/wps10-suite.ctl#L60)

After adding the control, I left the input empty and choose the same file with both upload control, the test suite can't start correctly, the result log file has the following exception:
Error in call to extension function {public static net.sf.saxon.om.DocumentInfo net.sf.saxon.functions.Extensions.transform(net.sf.saxon.expr.XPathContext,javax.xml.transform.Templates,net.sf.saxon.om.NodeInfo,net.sf.saxon.om.SequenceIterator) throws net.sf.saxon.trans.XPathException}: Integer division by zero
Result: Failed
<img width="1392" alt="Test parameters" src="https://user-images.githubusercontent.com/50437972/98806322-f9fe2500-2453-11eb-8a92-05cfd3a1bd75.png">

The sample xml file is zipped and attached below. I wonder if this error is related to the new upload control wps10-suite.ctl file. Please tell me if I need to provide more information, thank you.
[50_wpsExecute_request_RawDataOutput.xml.zip](https://github.com/opengeospatial/ets-wps10/files/5523684/50_wpsExecute_request_RawDataOutput.xml.zip)

**Comment by arieslai** [comment]
The log result file is attached too.
[s0002 (1).zip](https://github.com/opengeospatial/ets-wps10/files/5523712/s0002.1.zip)

**Comment by dstenger** [comment]
Following branch is used: https://github.com/opengeospatial/ets-wps10/tree/testng-develop

@keshav-nangare Can you please investigate and try to solve the described problem?

**Comment by keshav-nangare** [comment]
@arieslai 

I am not able to reproduce this issue on local environment. I installed the teamengine version 5.5-SNAPSHOT and test suite version 0.1-SNAPSHOT. Followed the steps as above, it worked fine and new html report is generated successfully with test failure.

Can you please provide steps to reproduce this issue? Also I didn't see any error related to divisible by zero.

**Comment by arieslai** [comment]
@keshav-nangare 

Sorry, it should be running with the command:
mvn clean install docker:run -Pdocker

Could you try the same steps on docker instead of local teamengine.

Thank you for your help.

**Comment by dstenger** [comment]
@keshav-nangare Can you please add a short comment after you will have provided your solution to @arieslai?

**Comment by keshav-nangare** [comment]
@dstenger @arieslai 

The `Pair` class used in the `ExecuteValidation` class has some access restrictions. I updated it with the `HashMap` class which works fine on the docker environment.

**Comment by arieslai** [comment]
The test can run successfully without the error, thank you!
