### ISSUE TITLE
Create one unit test

### ISSUE THREAD

**Issue by arieslai** [opengeospatial/ets-wps10#18]

**Comment by arieslai** [comment]
Create an integration test of the test suite at [src/test/java/org/opengis/cite/wps10/VerifyTestNGController.java](https://github.com/opengeospatial/ets-wps10/blob/b808569046a21b71bbe3239c20935640c1738ff7/src/test/java/org/opengis/cite/wps10/VerifyTestNGController.java#L55)

**Comment by dstenger** [comment]
Beta release is prepared: opengeospatial/te-releases#323
