### ISSUE TITLE
ETS throws an Out of memory error due to the DescribeProcess (ALL) response being too large

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ets-wps10#20]
The ETS throws an Out of memory error due to the DescribeProcess (ALL) response being too large.

We need to revise the HTTPPOSTTransferredXMLDescribeProcessValidation() method to select a small number of processes from the GetCapabilities response and then perform a DescribeProcess validation for that small number of processes.

https://github.com/opengeospatial/ets-wps10/blob/main/src/main/java/org/opengis/cite/wps10/level1/DescribeProcessValidation.java

**Comment by ghobona** [comment]
Suggested steps:

1. Run a GetCapabilities request
2. Extract the identifier of one of the processes
3. Use the extracted identifier in a DescribeProcess request

**Comment by dstenger** [comment]
@arieslai After merging your pull request I am getting test failures when running `mvn clean install site docker:run -Pintegration-tests,docker`.

```
Results :

Failed tests: 
  VerifyTestNGController.doTestRun:75 Unexpected number of fail verdicts. expected:<0> but was:<1>

Tests run: 20, Failures: 1, Errors: 0, Skipped: 2
```

Can you please check this?

**Comment by dstenger** [comment]
@arieslai 

I expect this failure not to be related to this fix as it also occurs with tag 0.7.

The used external services probably changed and is causing the failure.

Can you please check this?

**Comment by dstenger** [comment]
Test `ExecuteHttpProtocolUsageValidation()` is not working with the used remote service anymore.

As the test needs some rework (see #22) anyway, we are commenting it until the rework will be finished.

**Comment by dstenger** [comment]
Test was commented out in https://github.com/opengeospatial/ets-wps10/issues/22#issuecomment-890053960 and all unit tests are passed successfully again.
