### ISSUE TITLE
Need to verify ATS

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-wps10#5]
# Summary

The test cannot be moved for approval because of inconsistencies in the ATS. There are currently two ATSs:
- One found in the document OGC 05-007r7 ([Annex B](http://portal.opengeospatial.org/files/?artifact_id=24151&version=3))
- One on the repository (source at [tree/master/src/site/resources](https://github.com/opengeospatial/ets-wps10/blob/master/src/site/resources/WPS%201.0%20ATS.html))

The one in the Annex B is more complete than the one in the source. In some cases the ATS in the source is more precise about the test.

Some Execute tests cannot be tested, because there is a lack of a common processes across WPSs that will allow to perform similar execute request for any WPS.

The one in the Annex B describes a part on client test, which is not implemented.

52North and Geomatys have been part of the process.
# Possible path to move forward
- Try to change the code to follow the ATS in the spec
- Define a simple process that implementers must implement
- Submit a corrigendum if appropriate
# Ideas about current issues

**A.4.3.4 Language selection and A.4.3.3 DescribeProcess operation response**
The language selection in the DescribeProcess and Execute operations could be treated like it is done in the GetCapabilities tests, i.e. for supported languages the response should contain the right xml:lang attribute and for not supported languages an exception report should be returned.

**About a process**
Ask implementers of WPS 1.0 to provide an echo process that takes each of the three input groups as input and also returns each of the three output groups (see an example attached). With this process we could test all kinds of input/output combinations. For the status checking (A.4.3.5) another process should be provided that runs for a certain amount of time (e.g. five seconds) and that supports status updates. We are using this already for our internal tests.

Example process:

```
<?xml version="1.0" encoding="UTF-8"?>
<wps:ProcessDescriptions xmlns:wps="http://www.opengis.net/wps/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ows="http://www.opengis.net/ows/1.1" xsi:schemaLocation="http://www.opengis.net/wps/1.0.0 http://schemas.opengis.net/wps/1.0.0/wpsDescribeProcess_response.xsd" xml:lang="en-US" service="WPS" version="1.0.0">
  <ProcessDescription statusSupported="true" storeSupported="true" wps:processVersion="1.0.0">
    <ows:Identifier>org.n52.wps.server.algorithm.test.DummyTestClass</ows:Identifier>
    <ows:Title>org.n52.wps.server.algorithm.test.DummyTestClass</ows:Title>
    <DataInputs>
      <Input minOccurs="0" maxOccurs="1">
        <ows:Identifier>ComplexInputData</ows:Identifier>
        <ows:Title>ComplexInputData</ows:Title>
        <ComplexData>
          <Default>
            <Format>
              <MimeType>text/xml</MimeType>
              <Schema>http://schemas.opengis.net/gml/2.1.2/feature.xsd</Schema>
            </Format>
          </Default>
          <Supported>
            <Format>
              <MimeType>text/xml</MimeType>
              <Schema>http://schemas.opengis.net/gml/2.1.2/feature.xsd</Schema>
            </Format>
          </Supported>
        </ComplexData>
      </Input>
      <Input minOccurs="0" maxOccurs="1">
        <ows:Identifier>LiteralInputData</ows:Identifier>
        <ows:Title>LiteralInputData</ows:Title>
        <LiteralData>
          <ows:DataType ows:reference="xs:string"/>
          <ows:AnyValue/>
        </LiteralData>
      </Input>
      <Input minOccurs="0" maxOccurs="1">
        <ows:Identifier>BBOXInputData</ows:Identifier>
        <ows:Title>BBOXInputData</ows:Title>
        <BoundingBoxData>
          <Default>
            <CRS>EPSG:4328</CRS>
          </Default>
          <Supported>
            <CRS>EPSG:5628</CRS>
          </Supported>
        </BoundingBoxData>
      </Input>
    </DataInputs>
    <ProcessOutputs>
      <Output>
        <ows:Identifier>ComplexOutputData</ows:Identifier>
        <ows:Title>ComplexOutputData</ows:Title>
        <ows:Abstract>ComplexOutputData</ows:Abstract>
        <ComplexOutput>
          <Default>
            <Format>
              <MimeType>application/x-jsongeometry</MimeType>
              <Encoding>UTF-8</Encoding>
            </Format>
          </Default>
          <Supported>
            <Format>
              <MimeType>application/x-jsongeometry</MimeType>
              <Encoding>UTF-8</Encoding>
            </Format>
          </Supported>
        </ComplexOutput>
      </Output>
      <Output>
        <ows:Identifier>LiteralOutputData</ows:Identifier>
        <ows:Title>LiteralOutputData</ows:Title>
        <ows:Abstract>LiteralOutputData</ows:Abstract>
        <LiteralOutput>
          <ows:DataType ows:reference="xs:string"/>
        </LiteralOutput>
      </Output>
      <Output>
        <ows:Identifier>BBOXOutputData</ows:Identifier>
        <ows:Title>BBOXOutputData</ows:Title>
        <ows:Abstract>BBOXOutputData</ows:Abstract>
        <BoundingBoxOutput>
          <Default>
            <CRS>EPSG:4328</CRS>
          </Default>
          <Supported>
            <CRS>EPSG:5628</CRS>
          </Supported>
        </BoundingBoxOutput>
      </Output>
    </ProcessOutputs>
  </ProcessDescription>
</wps:ProcessDescriptions>

```

**Comment by bermud** [comment]
In conversations with the ATS editors. A call is to be scheduled soon.

**Comment by bermud** [comment]
At the call on 20160411 Ben reported no issues with the current GitHub ATS and ETS. The only problem is the execute test, which creating a generic test will be challenging. Ben, will draft an echo test process that implementers will be required to implement.

**Comment by bermud** [comment]
We might need to test some basic types: numbers types, strings, booleans and GML.

**Comment by bermud** [comment]
@dstenger, please provide recommendation about how to move forward.

**Comment by ghobona** [comment]
This test suite is being replaced with one that is implemented using TestNG.
