### ISSUE TITLE
 Multiple Exceptions in ExceptionReport

### ISSUE THREAD

**Issue by gfenoy** [opengeospatial/ets-wps10#6]
When using the WPS test suite available at http://cite.opengeospatial.org/te2/, I have one test which failed. I suppose that the error is in the testing suite and not in the software tested.

Indeed, we can see in section 8.5 of the clause 8 of [OGC 06-121r3] that there is an example of Exception report containing two Exception nodes. Furthermore, looking at the UML diagram, we can see that an Exception node is "1..*" meaning that and ExceptionRepport can contain one or more Exception nodes.

The issue reported is the following:

--

`Test owsTests:ows-OWS.GetCapabilities-Exceptions.5 type Mandatory default result Passed (s0025/d1162e143_1/d1162e219_1/d253e54_1/d253e350_1)

Assertion: In the event that a GetCapabilities request cannot be processed for any reason, the response entity shall include an exception report. The exception code must be one of those listed in Table 5.

Message d253e1692_1:
   GetCapabilities with an incorrect KVP query string, triggering the missing parameter value exception.  Pass if all of the following conditions are true: (1) the response is schema valid; (2) the root document is an ows:ExceptionReport document; (3) the ExceptionReport shall have the "MissingParameterValue" exception code, for both the request and service.

Message d253e1697_1:
   Query String: http://www.zoo-project.org/cgi-bin/zoo_loader3.cgi?request~GetCapabilities!service~!WPSversion~1.0.0

Request d253e1701_1:
   Method: get
   URL: http://www.zoo-project.org/cgi-bin/zoo_loader3.cgi?request~GetCapabilities!service~!WPSversion~1.0.0
   Response from parser parsers:XMLValidatingParser:
      <ows:ExceptionReport xmlns:ows="http://www.opengis.net/ows/1.1"
                     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                     version="1.1.0"
                     xml:lang="fr-FR"
                     xsi:schemaLocation="http://www.opengis.net/ows/1.1 http://schemas.opengis.net/ows/1.1.0/owsExceptionReport.xsd">
  <ows:Exception exceptionCode="MissingParameterValue" locator="request">
      <ows:ExceptionText>Mandatory parameter &lt;request&gt; was not specified</ows:ExceptionText>
  </ows:Exception>
  <ows:Exception exceptionCode="MissingParameterValue" locator="service">
      <ows:ExceptionText>Mandatory parameter &lt;service&gt; was not specified</ows:ExceptionText>
  </ows:Exception>
   </ows:ExceptionReport>

Message d253e1773_1:
   FAILURE: The returned exception report was expected to contain an exceptionCode of "MissingParameterValue" and a locator value of "service" or "request".

Message d253e1776_1:
   Returned exception code was: "MissingParameterValue MissingParameterValue"

Message d253e1778_1:
   Returned locator was: "request service"

Result: Failed`

--

Please let me know if I have to fix the software or if my feeling that the test suite is wrong were justified.

**Comment by bermud** [comment]
@gfenoy, This seems like a bug. We will investigate. Thank you for reporting.

**Comment by bermud** [comment]
Maybe the  <ctl:function name="wpsFunctions:checkExceptionReport"> needs to be updated to handle multiple Exceptions.

https://github.com/opengeospatial/ets-wps10/blob/master/src/main/scripts/ctl/functions.xml

This is what is currently being sent by the server:

```
<?xml version="1.0" encoding="utf-8"?>
<ows:ExceptionReport xmlns:ows="http://www.opengis.net/ows/1.1"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.opengis.net/ows/1.1 http://schemas.opengis.net/ows/1.1.0/owsExceptionReport.xsd"
    xml:lang="fr-FR" version="1.1.0">
    <ows:Exception exceptionCode="MissingParameterValue" locator="request">
        <ows:ExceptionText>Mandatory parameter &lt;request&gt; was not specified</ows:ExceptionText>
    </ows:Exception>
    <ows:Exception exceptionCode="MissingParameterValue" locator="service">
        <ows:ExceptionText>Mandatory parameter &lt;service&gt; was not specified</ows:ExceptionText>
    </ows:Exception>
</ows:ExceptionReport>
```

**Comment by keshav-nangare** [comment]
We found wrong condition in OWS file, which is used to test the attribute value, that's why it returns the false and test get fail.

Fixed with this commit 73ab774b9311a7ce0cf7b455a1ed8cbc46831d33

**Comment by keshav-nangare** [comment]
Following is the result after changes:

![wps_test_result](https://cloud.githubusercontent.com/assets/14732650/14678449/53f6aa2a-0733-11e6-9fb9-3f43f9d30cfc.png)

**Comment by gfenoy** [comment]
Very nice.
Thanks a lot for the feedbacks and the fixes.

**Comment by bermud** [comment]
Great that we solved this issue. I will proceed doing the release.

**Comment by gfenoy** [comment]
Thanks a lot for releasing, the new tests I have run on te2 have succeeded.
