### ISSUE TITLE
Cannot find the declaration of element wps:Capabilities

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-wps10#9]
The following server is not passing. 

http://demo.pywps.org/cite/wps.

The server might be returning the expected content based on
the request, though the test is expecting an exception.

Test owsTests:ows-OWS.GetCapabilities-Exceptions.1 type Mandatory default result Passed (s0053/d1162e143_1/d1162e219_1/d253e54_1/d253e263_1)

Assertion: In the event that a GetCapabilities request cannot be processed for any reason, the response entity shall include an exception report. The exception code must be one of those listed in Table 5.

Message d253e1209_1:
  GetCapabilities with no service parameter.  Pass if all of the following conditions are true: (1) the response is schema valid; (2) the root document is an ows:ExceptionReport document; (3) the ExceptionReport shall have the "MissingParameterValue" exception code; (4) theExceptionReport @locator value shall be that of the missing parameter.

Message d253e1211_1:
  Version parameter: 1.0.0

Request d253e1215_1:
  Method: get
  URL: http://demo.pywps.org/cite/wps?service=WPS&version=1.0.0&request=GetCapabilities&version=1.0.0&request=GetCapabilities
  Response from parser parsers:XMLValidatingParser:

  Messages from parser parsers:XMLValidatingParser:
       Validation error:
 cvc-elt.1.a: Cannot find the declaration of element 'wps:Capabilities'.
1 validation error detected.

Message d253e1258_1:
  FAILURE: Missing or invalid response entity.

Result: Failed

**Comment by bpross-52n** [comment]
I tested this recently and the test passes. Log:

Log for test s0011/d1162e143_1/d1162e219_1/d253e54_1/d253e263_1

Test owsTests:ows-OWS.GetCapabilities-Exceptions.1 type Mandatory default result Passed (s0011/d1162e143_1/d1162e219_1/d253e54_1/d253e263_1)

Assertion: In the event that a GetCapabilities request cannot be processed for any reason, the response entity shall include an exception report. The exception code must be one of those listed in Table 5.

Message d253e1209_1:
   GetCapabilities with no service parameter.  Pass if all of the following conditions are true: (1) the response is schema valid; (2) the root document is an ows:ExceptionReport document; (3) the ExceptionReport shall have the "MissingParameterValue" exception code; (4) theExceptionReport @locator value shall be that of the missing parameter.

Message d253e1211_1:
   Version parameter: 1.0.0

Request d253e1215_1:
   Method: get
   URL: http://demo.pywps.org/cite/wps?version=1.0.0&request=GetCapabilities
   Response from parser parsers:XMLValidatingParser:
      <ows:ExceptionReport xmlns:ows="http://www.opengis.net/ows/1.1"
                     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                     version="1.0.0"
                     xsi:schemaLocation="http://www.opengis.net/ows/1.1 http://schemas.opengis.net/ows/1.1.0/owsExceptionReport.xsd">
  <ows:Exception exceptionCode="MissingParameterValue" locator="service">
      <ows:ExceptionText>service</ows:ExceptionText>
  </ows:Exception>
   </ows:ExceptionReport>

Result: Passed

**Comment by tomkralidis** [comment]
cc @jachym

@bpross-52n thanks for the feedback.  Turns out I was entering the full GetCapabilities URL (as is convention in some other CITE test suites).  Providing just the base URL works as expected.

It would be valuable for the input form to make clear that a full GetCapabilities URL is not required and / or the CITE WPS test suite constructs the GetCapabilities URL automagically.

**Comment by bermud** [comment]
@keshav-nangare, Please allow to test a service if the whole URL is provided. So both URLs should be OK to  test:
-  http://demo.pywps.org/cite/wps?version=1.0.0&request=GetCapabilities  
- http://demo.pywps.org/cite/wps

**Comment by keshav-nangare** [comment]
Fixed with this commit: f960efbd9870ef8ae3e5ecbb31f591fd0a29912b

**Comment by bermud** [comment]
@keshav-nangare, please merge to branch and update the release notes.
